src/apps/resources/urls.py
from django.conf.urls import url

from .views import *


# Model3d urls
urlpatterns = [
    url(
        r'^resources/model3d/(?P<pk>\d+)/$',
        Model3dDetailView.as_view(),
        name='model3d_detail'
    ),
    url(
        r'^resources/model3d/$',
        Model3dListView.as_view(),
        name='model3d_list'
    ),
    url(
        r'^resources/model3d/order/(?P<field>\w+)/type/(?P<order_type>\w+)/$',
        Model3dListView.as_view(),
        name='model3d_list_ordered'
    ),
    url(
        r'^resources/model3d/new/$',
        Model3dCreateView.as_view(),
        name='model3d_creation'
    ),
]


# Badge urls
urlpatterns += [
    url(
        r'^resources/badge/(?P<pk>\d+)/$',
        BadgeDetailView.as_view(),
        name='badge_detail'
    ),
    url(
        r'^resources/badge/$',
        BadgeListView.as_view(),
        name='badge_list'
    ),
    url(
        r'^resources/badge/new/$',
        BadgeCreateView.as_view(),
        name='badge_creation'
    ),
]

src/apps/users/urls.py
from django.conf.urls import url, include

from rest_framework import routers

from .views import UserDetailView, UserListView, UserApiDetail


urlpatterns = [
    url(
        r'^users/(?P<pk>\d+)/$',
        UserDetailView.as_view(),
        name='user_detail'
    ),
    url(
        r'^users/$',
        UserListView.as_view(),
        name='user_list'
    ),
]

router = routers.DefaultRouter()

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns += [
    url(r'^', include(router.urls)),
    url(r'^userbadgesapi/(?P<id>[0-9]+)/$', UserApiDetail.as_view()),
]

src/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views


# Administration urls
urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

# Apps urls
urlpatterns += [
    url(r'^', include('apps.core.urls', namespace='core')),
    url(r'^', include('apps.users.urls', namespace='users')),
    url(r'^', include('apps.resources.urls', namespace='resources')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/resources/badge_detail.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ view.title }}</h1>
    Titre : {{ object.title }} <br/>
    Description : {{ object.description }} <br/>
    <br/>
    <a href="{% url "resources:badge_list" %}">Retour à la liste des badges</a>
{% endblock %}

src/templates/resources/badge_form.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ view.title }}</h1>
    <form class="form-horizontal" action="" method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="form-group">
            <label class="col-sm-2 control-label">
                {{ form.title.label }}
            </label>
            <div class="col-sm-10 col-md-4">
                {{ form.title }}
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">
                {{ form.description.label }}
            </label>
            <div class="col-sm-10 col-md-4">
                {{ form.description }}
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-10 col-md-6">
                <button class="btn btn-primary pull-right" type="submit">
                    <i class="fa fa-check"></i> Enregistrer
                </button>
            </div>
        </div>
    </form>
{% endblock %}

src/templates/resources/badge_list.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ view.title }}</h1>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>
                    #
                </th>
                <th>
                    Titre
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for obj in object_list %}
                <tr>
                    <td>{{ obj.pk }}</td>
                    <td>
                        <a href="{{ obj.get_absolute_url }}" title="Consulter le badge">
                            {{ obj.title }}
                        </a>
                    </td>
                    <td>
                        <a class="btn btn-primary btn-xs" href="{% url "resources:badge_detail" obj.pk %}" title="Consulter">
                            <i class="fa fa-plus"></i>
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <br/>
    <a href="{% url "resources:badge_creation" %}">Créer un badge</a>
{% endblock %}

src/templates/resources/model3d_detail.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ view.title }}</h1>
    <p>titre : {{ object.title }}</p>
    <p>nb vues : {{ object.views }}</p>
    <p>image : {{ object.image }}</p>
    {% if object.image %}
        <img src="{{ MEDIA_URL }}{{ object.image }}"/>
    {% endif %}
{% endblock %}

src/templates/resources/model3d_form.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ view.title }}</h1>
    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="form-group">
            <label class="col-sm-2 control-label">
                {{ form.title.label }}
            </label>
            <div class="col-sm-10 col-md-4">
                {{ form.title }}
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">
                {{ form.description.label }}
            </label>
            <div class="col-sm-10 col-md-4">
                {{ form.description }}
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">
                {{ form.image.label }}
            </label>
            <div class="col-sm-10 col-md-4">
                {{ form.image }}
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-10 col-md-6">
                <button class="btn btn-primary pull-right" type="submit">
                    <i class="fa fa-check"></i> Enregistrer
                </button>
            </div>
        </div>
    </form>
{% endblock %}

src/templates/resources/model3d_list.html
{% extends "base.html" %}
{% load orderlist %}

{% block content %}
    <h1>{{ view.title }}</h1>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th>
                    # {% orderlist "resources:model3d_list_ordered" "id" %}
                </th>
                <th>
                    Titre {% orderlist "resources:model3d_list_ordered" "title" %}
                </th>
                <th>
                    Créateur du modèle
                </th>
                <th>
                    Nombre de vues {% orderlist "resources:model3d_list_ordered" "views" %}
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for obj in object_list %}
                <tr>
                    <td>{{ obj.pk }}</td>
                    <td>
                        <a href="{{ obj.get_absolute_url }}" title="Consulter le modèle 3D">
                            {{ obj.title }}
                        </a>
                    </td>
                    <td>
                        <a href="{% url "users:user_detail" obj.user.pk %}" title="Consulter l'utilisateur">
                            {{ obj.user }}
                        </a>
                    </td>
                    <td>
                        {{ obj.views }}
                    </td>
                    <td>
                        <a class="btn btn-primary btn-xs" href="{% url "resources:model3d_detail" obj.pk %}" title="Consulter">
                            <i class="fa fa-plus"></i>
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <br/>
    <a href="{% url "resources:model3d_creation" %}">Créer un modèle 3D</a>
{% endblock %}