src/apps/resources/urls.py
from django.conf.urls import url

from .views import *


# Model3d urls
urlpatterns = [
    url(
        r'^resources/model3d/(?P<pk>\d+)/$',
        Model3dDetailView.as_view(),
        name='model3d_detail'
    ),
    url(
        r'^resources/model3d/$',
        Model3dListView.as_view(),
        name='model3d_list'
    ),
    url(
        r'^resources/model3d/order/(?P<field>\w+)/type/(?P<order_type>\w+)/$',
        Model3dListView.as_view(),
        name='model3d_list_ordered'
    ),
    url(
        r'^resources/model3d/new/$',
        Model3dCreateView.as_view(),
        name='model3d_creation'
    ),
]


# Badge urls
urlpatterns += [
    url(
        r'^resources/badge/(?P<pk>\d+)/$',
        BadgeDetailView.as_view(),
        name='badge_detail'
    ),
    url(
        r'^resources/badge/$',
        BadgeListView.as_view(),
        name='badge_list'
    ),
    url(
        r'^resources/badge/new/$',
        BadgeCreateView.as_view(),
        name='badge_creation'
    ),
]

src/apps/users/urls.py
from django.conf.urls import url, include

from rest_framework import routers

from .views import UserDetailView, UserListView, UserApiDetail


urlpatterns = [
    url(
        r'^users/(?P<pk>\d+)/$',
        UserDetailView.as_view(),
        name='user_detail'
    ),
    url(
        r'^users/$',
        UserListView.as_view(),
        name='user_list'
    ),
]

router = routers.DefaultRouter()

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns += [
    url(r'^', include(router.urls)),
    url(r'^userbadgesapi/(?P<id>[0-9]+)/$', UserApiDetail.as_view()),
]

src/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views


# Administration urls
urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

# Apps urls
urlpatterns += [
    url(r'^', include('apps.core.urls', namespace='core')),
    url(r'^', include('apps.users.urls', namespace='users')),
    url(r'^', include('apps.resources.urls', namespace='resources')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
    <head>
     <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">

        <title>Sketchfab : projet d'entretien</title>

        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

        <!-- Optional theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

        <!-- Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

        <script src="https://use.fontawesome.com/aacaeae8ce.js"></script>
    </head>
    <body>
        {% block content %}
        {% endblock %}
    </body>
</html>

src/templates/index.html
{% extends "base.html" %}

{% block content %}
    <h1>Bienvenue sur l'exercice d'entretien Sketchfab !</h1>
    <p>
        <ul>
            <li><a href="{% url "resources:model3d_list" %}">Modèles 3D</a></li>
            <li><a href="{% url "resources:badge_list" %}">Badges</a></li>
            <li><a href="{% url "users:user_list" %}">Utilisateurs</a></li>
        </ul>
    </p>
{% endblock %}